// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqqvzusebkmiybzoxiro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxcXZ6dXNlYmttaXliem94aXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTcwODksImV4cCI6MjA2NDQzMzA4OX0.hdSUeA9McyKLT1nDBegaCk-6YRpHW_eX83xet9YLPT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);